### ISSUE TITLE
Video is not shown

### ISSUE THREAD

**Issue by april-iam** [globalmooccampus/version-2.0#4]
http://kc4dh.com/v2/beta/coursera/course/softwaresec
http://kc4dh.com/v2/beta/coursera/course/cic
http://kc4dh.com/v2/beta/coursera/course/arthistory
http://kc4dh.com/v2/beta/coursera/course/ntusym
http://kc4dh.com/v2/beta/coursera/course/cdt208
http://kc4dh.com/v2/beta/coursera/course/design
http://kc4dh.com/v2/beta/coursera/course/kunqu
http://kc4dh.com/v2/beta/coursera/course/drugsandbrain
http://kc4dh.com/v2/beta/coursera/course/pkubioinfo
http://kc4dh.com/v2/beta/coursera/course/genes
http://kc4dh.com/v2/beta/coursera/course/ntusym
http://kc4dh.com/v2/beta/coursera/course/sysbio
http://kc4dh.com/v2/beta/coursera/course/neuraldata
http://kc4dh.com/v2/beta/coursera/course/pregnancychildbirth
http://kc4dh.com/v2/beta/coursera/course/pregnancychildbirth
http://kc4dh.com/v2/beta/coursera/course/sysbio
http://kc4dh.com/v2/beta/coursera/course/brainspace
http://kc4dh.com/v2/beta/coursera/course/bioinformatics
http://kc4dh.com/v2/beta/coursera/course/emergenceoflife
http://kc4dh.com/v2/beta/coursera/course/statreasoning
http://kc4dh.com/v2/beta/coursera/course/neuromarketing
http://kc4dh.com/v2/beta/coursera/course/interorg
http://kc4dh.com/v2/beta/coursera/course/assetpricing
http://kc4dh.com/v2/beta/coursera/course/sustainableag
http://kc4dh.com/v2/beta/coursera/course/designingcities
http://kc4dh.com/v2/beta/coursera/course/uffinancialplanning
http://kc4dh.com/v2/beta/coursera/course/socialentrepeneur
http://kc4dh.com/v2/beta/coursera/course/sustaininprac
http://kc4dh.com/v2/beta/coursera/course/unethicaldecision
http://kc4dh.com/v2/beta/coursera/course/mafash
http://kc4dh.com/v2/beta/coursera/course/marketing
http://kc4dh.com/v2/beta/coursera/course/innovativeideas
http://kc4dh.com/v2/beta/coursera/course/design
http://kc4dh.com/v2/beta/coursera/course/chemistry
http://kc4dh.com/v2/beta/coursera/course/ntusym
http://kc4dh.com/v2/beta/coursera/course/chemhealth
http://kc4dh.com/v2/beta/coursera/course/ggp
http://kc4dh.com/v2/beta/coursera/course/mmds
http://kc4dh.com/v2/beta/coursera/course/pkubioinfo
http://kc4dh.com/v2/beta/coursera/course/android
http://kc4dh.com/v2/beta/coursera/course/proglang

**Comment by hassanabidpk** [comment]
Fixed. Instead of Video, an Image will be shown ( because Coursera doesn't provide YouTube video for it)
